services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    restart: on-failure
  minio:
    image: minio/minio:${MINIO_VERSION}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: [ "server", "/data" ]
    ports:
      - 9000:9000
    restart: on-failure
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: h2 # TODO: Delete this and use mysql instead.
      KEYCLOAK_IMPORT: /tmp/${KEYCLOAK_REALM}-realm.json
    ports:
      - 8180:8080
    volumes:
      - ../keycloak/${KEYCLOAK_REALM}-realm.json:/tmp/${KEYCLOAK_REALM}-realm.json
    restart: on-failure
