services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_RESERVATIO_DATABASE: ${MYSQL_RESERVATIO_DATABASE}
      MYSQL_RESERVATIO_USER: ${MYSQL_RESERVATIO_USER}
      MYSQL_RESERVATIO_PASSWORD: ${MYSQL_RESERVATIO_PASSWORD}
      MYSQL_KEYCLOAK_DATABASE: ${MYSQL_KEYCLOAK_DATABASE}
      MYSQL_KEYCLOAK_USER: ${MYSQL_KEYCLOAK_USER}
      MYSQL_KEYCLOAK_PASSWORD: ${MYSQL_KEYCLOAK_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ../mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: on-failure
  minio:
    image: minio/minio:${MINIO_VERSION}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: [ "server", "/data" ]
    ports:
      - 9000:9000
    restart: on-failure
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_DATABASE: ${MYSQL_KEYCLOAK_DATABASE}
      DB_USER: ${MYSQL_KEYCLOAK_USER}
      DB_PASSWORD: ${MYSQL_KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/${KEYCLOAK_REALM}-realm.json
    ports:
      - ${KEYCLOAK_EXPOSED_PORT}:8080
    volumes:
      - ../keycloak/${KEYCLOAK_REALM}-realm.json:/tmp/${KEYCLOAK_REALM}-realm.json
    restart: on-failure
