services:
  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    restart: on-failure
  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: [ "server", "/data" ]
    ports:
      - 9000:9000
    restart: on-failure
  backend:
    build: ../../backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      RESERVATIO_MINIO_ENDPOINT: http://minio:9000
      RESERVATIO_MINIO_USERNAME: ${MINIO_ROOT_USER}
      RESERVATIO_MINIO_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - 8080:8080
    restart: on-failure
  frontend:
    build: ../../frontend
    ports:
      - 3000:3000
    restart: on-failure
