services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_RESERVATIO_DATABASE: ${MYSQL_RESERVATIO_DATABASE}
      MYSQL_RESERVATIO_USER: ${MYSQL_RESERVATIO_USER}
      MYSQL_RESERVATIO_PASSWORD: ${MYSQL_RESERVATIO_PASSWORD}
      MYSQL_KEYCLOAK_DATABASE: ${MYSQL_KEYCLOAK_DATABASE}
      MYSQL_KEYCLOAK_USER: ${MYSQL_KEYCLOAK_USER}
      MYSQL_KEYCLOAK_PASSWORD: ${MYSQL_KEYCLOAK_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ../mysql/volume:/var/lib/mysql
      - ../mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: on-failure
  minio:
    image: minio/minio:${MINIO_VERSION}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: [ "server", "/data" ]
    ports:
      - 9000:9000
    volumes:
      - ../minio/volume:/data
    restart: on-failure
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_DATABASE: ${MYSQL_KEYCLOAK_DATABASE}
      DB_USER: ${MYSQL_KEYCLOAK_USER}
      DB_PASSWORD: ${MYSQL_KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/${KEYCLOAK_REALM}-realm.json
      KEYCLOAK_FRONTEND_URL: http://localhost:${KEYCLOAK_EXPOSED_PORT}/auth
    ports:
      - ${KEYCLOAK_EXPOSED_PORT}:8080
    volumes:
      - ../keycloak/${KEYCLOAK_REALM}-realm.json:/tmp/${KEYCLOAK_REALM}-realm.json
    restart: on-failure
  backend:
    build: ../../backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_RESERVATIO_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_RESERVATIO_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_RESERVATIO_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
      RESERVATIO_LOAD_TEST_DATA: 'false'
      RESERVATIO_CORS_ALLOWED_ORIGINS_0_: http://frontend:3000
      RESERVATIO_CORS_ALLOWED_ORIGINS_1_: http://localhost:3000
      RESERVATIO_MINIO_ENDPOINT: http://minio:9000
      RESERVATIO_MINIO_USERNAME: ${MINIO_ROOT_USER}
      RESERVATIO_MINIO_PASSWORD: ${MINIO_ROOT_PASSWORD}
      RESERVATIO_KEYCLOAK_USERNAME: ${RESERVATIO_KEYCLOAK_USERNAME}
      RESERVATIO_KEYCLOAK_PASSWORD: ${RESERVATIO_KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    restart: on-failure
  frontend:
    build:
      context: ../../frontend
      args:
        REACT_APP_KEYCLOAK_AUTH_SERVER_URL: http://localhost:${KEYCLOAK_EXPOSED_PORT}/auth
        REACT_APP_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        REACT_APP_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_RESOURCE}
        REACT_APP_BACKEND_HOST: http://localhost:8080
    ports:
      - 3000:3000
    restart: on-failure
