spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # TODO: Temporary
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/reservatio
    username: reservatio
    password: reservatio
    hikari:
      initialization-fail-timeout: -1